"""fix uuid types for sleep workout recovery sleep_id

Revision ID: 6c83f25a3948
Revises: 7dbe29035363
Create Date: 2026-02-27 19:59:10.216845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c83f25a3948'
down_revision: Union[str, Sequence[str], None] = '7dbe29035363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('data_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('alcohol_units', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('caffeine', sa.Boolean(), nullable=True),
    sa.Column('late_caffeine', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date')
    )
    op.create_table('whoop_cycles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strain_score', sa.Float(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whoop_recovery',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=False),
    sa.Column('sleep_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_calibrating', sa.Boolean(), nullable=True),
    sa.Column('recovery_score', sa.Integer(), nullable=True),
    sa.Column('hrv_rmssd_milli', sa.Float(), nullable=True),
    sa.Column('resting_heart_rate', sa.Integer(), nullable=True),
    sa.Column('spo2_percentage', sa.Float(), nullable=True),
    sa.Column('skin_temp_celsius', sa.Float(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('whoop_sleep',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nap', sa.Boolean(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_in_bed_milli', sa.BigInteger(), nullable=True),
    sa.Column('light_sleep_milli', sa.BigInteger(), nullable=True),
    sa.Column('slow_wave_milli', sa.BigInteger(), nullable=True),
    sa.Column('rem_sleep_milli', sa.BigInteger(), nullable=True),
    sa.Column('awake_count', sa.Integer(), nullable=True),
    sa.Column('sleep_cycle_count', sa.Integer(), nullable=True),
    sa.Column('sleep_performance_pct', sa.Float(), nullable=True),
    sa.Column('sleep_consistency_pct', sa.Float(), nullable=True),
    sa.Column('sleep_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('sleep_debt_milli', sa.BigInteger(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('whoop_workouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cycle_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('sport_name', sa.String(length=100), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('strain_score', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('kilojoules', sa.Float(), nullable=True),
    sa.Column('distance_meter', sa.Float(), nullable=True),
    sa.Column('zone_zero_milli', sa.BigInteger(), nullable=True),
    sa.Column('zone_one_milli', sa.BigInteger(), nullable=True),
    sa.Column('zone_two_milli', sa.BigInteger(), nullable=True),
    sa.Column('zone_three_milli', sa.BigInteger(), nullable=True),
    sa.Column('zone_four_milli', sa.BigInteger(), nullable=True),
    sa.Column('zone_five_milli', sa.BigInteger(), nullable=True),
    sa.Column('score_state', sa.String(length=50), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whoop_workouts')
    op.drop_table('whoop_sleep')
    op.drop_table('whoop_recovery')
    op.drop_table('whoop_cycles')
    op.drop_table('journal_entries')
    op.drop_table('ai_insights')
    # ### end Alembic commands ###
